# Generated by Django 2.2 on 2019-05-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190513_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursetag',
            name='tag',
            field=models.CharField(max_length=100, verbose_name='标签'),
        ),
    ]
